### ISSUE TITLE
Check for custom serialisation routines not passing on `const` types

### ISSUE THREAD

**Issue by rohanmclure** [TESSEorg/ttg#102]
Using Madness for serialisation (but the PaRSEC runtime), I had a trivially copyable structure called `Key` with its own custom load / store methods as follows:

```c++
    template <class Archive>
    struct ArchiveStoreImpl<Archive, Key> {
      static inline void store(const Archive &ar, const Key &k) {
/* body */
      }
    };

template <class Archive>
struct ArchiveLoadImpl<Archive, Key> {
      static inline void load(const Archive &ar, Key &k) {
/* body */
      }
    };
```

These methods were always being used for serialisation, however it seems that this static evaluation `
detail::is_madness_user_buffer_serializable_v<T>` returns `false` with type parameter `const Key` but true with type parameter `Key`. 

Which means that `const Key` is not viewed as not having its own specialised serialisation methods, and leading `pack` in `ttg/ttg/parsec/ttg.h:546-550` not being run so as to write the size of the object to the buffer.

```c++
      if constexpr (!ttg::default_data_descriptor<T>::serialize_size_is_const) {
        const ttg_data_descriptor *dSiz = ttg::get_data_descriptor<uint64_t>();
        dSiz->pack_payload(&payload_size, sizeof(uint64_t), pos, bytes);
        pos += sizeof(uint64_t);
      }
```

That is size is not properly detected and serialised for `const` qualified objects. The solution currently is to add custom `store` methods for `const Key`.

**Comment by evaleev** [comment]
@rohanmclure serialization is being reworked currently ... just merged another batch of changes into `master` which tests for this issue (https://github.com/TESSEorg/ttg/blob/master/tests/unit/serialization.cc#L514). Please test against `master`, it should not be necessary to specialize serialization methods for `const T`, only for `T`.

**Comment by evaleev** [comment]
@rohanmclure I presume this works in master now, please reopen if not.
