### ISSUE TITLE
Build fails - fatal error: madness/world/world.h: No such file or directory

### ISSUE THREAD

**Issue by josephjohnjj** [TESSEorg/ttg#105]
I used an external PaRSEC (https://bitbucket.org/herault/parsec/src/termdet/) for the build. External Madness was _not_ used. The cmake command used is :

cmake ..  -DPaRSEC_ROOT_DIR=/home/joseph/parsec/build/install -DCMAKE_INSTALL_PREFIX=/home/joseph/ttg/build/install -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc

The build fails with the errors:

/home/joseph/ttg/examples/floyd-warshall/floyd_warshall_df.cc:34:10: fatal error: madness/world/world.h: No such file or directory
   34 | #include <madness/world/world.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/joseph/ttg/examples/ge/ge_df.cc:25:10: fatal error: madness/world/world.h: No such file or directory
   25 | #include <madness/world/world.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

Am I missing something?

**Comment by therault** [comment]
Please provide the output of your cmake (from a clean build directory), and
the compile line that fails.

Thanks,
Thomas

**Comment by josephjohnjj** [comment]
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- EIGEN3_FOUND=1
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET OPTIONAL_COMPONENTS serialization
-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found boost_serialization 1.70.0 at /usr/local/lib/cmake/boost_serialization-1.70.0
--   libboost_serialization.a
-- Adding boost_serialization dependencies: headers
-- Found Boost at /usr/local/lib/cmake/Boost-1.70.0/BoostConfig.cmake; includes Boost::serialization
CMake Warning at cmake/modules/FindOrFetchCereal.cmake:4 (find_package):
  By not providing "Findcereal.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "cereal", but
  CMake did not find one.

  Could not find a package configuration file provided by "cereal" with any
  of the following names:

    cerealConfig.cmake
    cereal-config.cmake

  Add the installation prefix of "cereal" to CMAKE_PREFIX_PATH or set
  "cereal_DIR" to a directory containing one of the above files.  If "cereal"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:54 (include)


-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long double
-- Check size of long double - done
-- Check size of long long
-- Check size of long long - done
-- Using CMAKE_INSTALL_PREFIX = /home/joseph/ttg/build/install
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- No CUDA support in BLAS++
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- blaspp_id = 9097d6b
-- Looking for BLAS libraries and options
[1mdefault (no library)[22m
   libs:   
   -DBLAS_FORTRAN_ADD_                             [31m no (didn't link: routine not found)[39m
   -DBLAS_FORTRAN_LOWER                            [31m no (didn't link: routine not found)[39m
   -DBLAS_FORTRAN_UPPER                            [31m no (didn't link: routine not found)[39m

[1mIntel MKL lp64,  GNU threads (gomp), gfortran[22m
   libs:  -lmkl_gf_lp64  -lmkl_gnu_thread -lmkl_core
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIntel MKL ilp64, GNU threads (gomp), gfortran[22m
   libs:  -lmkl_gf_ilp64 -lmkl_gnu_thread -lmkl_core
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIntel MKL lp64,  sequential, gfortran[22m
   libs:  -lmkl_gf_lp64  -lmkl_sequential -lmkl_core
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIntel MKL ilp64, sequential, gfortran[22m
   libs:  -lmkl_gf_ilp64 -lmkl_sequential -lmkl_core
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIntel MKL lp64,  sequential, ifort[22m
   libs:  -lmkl_intel_lp64  -lmkl_sequential -lmkl_core
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIntel MKL ilp64, sequential, ifort[22m
   libs:  -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIBM ESSL int (lp64), multi-threaded, with OpenMP[22m
   libs:  -lesslsmp
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIBM ESSL int64 (ilp64), multi-threaded, with OpenMP[22m
   libs:  -lesslsmp6464
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIBM ESSL int (lp64), sequential[22m
   libs:  -lessl
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mIBM ESSL int64 (ilp64), sequential[22m
   libs:  -lessl6464
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mOpenBLAS[22m
   libs:  -lopenblas
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mApple Accelerate[22m
   libs:  -framework Accelerate
   -DBLAS_FORTRAN_ADD_                             [31m no (library not found)[39m

[1mgeneric[22m
   libs:  -lblas
   -DBLAS_FORTRAN_ADD_                             [34m yes[39m

[34m   Found BLAS library: -lblas[39m
-- Checking BLAS library version
-- Checking BLAS complex return type
[34m   BLAS (zdotc) returns complex (GNU gfortran convention)[39m
-- Checking BLAS float return type
[34m   BLAS (sdot) returns float as float (standard)[39m
-- Checking for CBLAS library 
[34m   Found CBLAS library [39m
-- Using CMAKE_INSTALL_PREFIX = /home/joseph/ttg/build/install
-- lapackpp_id = 213d13e
-- Check for BLAS++
   BLAS++ already included
-- Looking for LAPACK libraries and options
   In BLAS library                                 [31m no (didn't link: routine not found)[39m
   -llapack                                        [34m yes[39m
[34m   Found LAPACK library: -llapack[39m
-- Checking LAPACK version
[34m   LAPACK version 3.09.00 (30900)[39m
-- Checking for XBLAS
[31m   XBLAS not found.[39m
-- Checking for LAPACKE library 
-- Checking for LAPACKE library -llapacke
[34m   Found LAPACKE library: -llapacke[39m
-- Looking for mkl_dimatcopy
-- Looking for mkl_dimatcopy - not found
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.17") found components: doxygen dot 
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- === BTAS Package/Feature Info ===
-- The following features have been enabled:

 * USE_BLAS_LAPACK, Will use BLAS and LAPACK linear algebra distributions via their BLAS++/LAPACK++ interfaces
 * TARGET_MAX_INDEX_RANK=6, default BTAS index type will use stack for rank<=6

-- The following OPTIONAL packages have been found:

 * Eigen3
 * Doxygen

-- The following REQUIRED packages have been found:

 * Git

-- The following features have been disabled:

 * BUILD_DEPS_FROM_SOURCE, Will build missing dependencies from source
 * BUILD_UNITTEST, Will build unit tests
 * ASSERT_THROWS, BTAS_ASSERT(x) will throw if x is false, and not be affected by NDEBUG

-- The following OPTIONAL packages have not been found:

 * cereal

-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE  found components: CXX 
-- Performing Test CXX_EXECUTION_NO_LINK_NEEDED
-- Performing Test CXX_EXECUTION_NO_LINK_NEEDED - Failed
-- 
-- Found Intel TBB: headers in /usr/local/include (interface version 10006), libs in /usr/local/lib
-- Performing Test CXX_EXECUTION_TBB_NEEDED
-- Performing Test CXX_EXECUTION_TBB_NEEDED - Success
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found HWLOC: /usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Performing Test PARSEC_HAVE_HWLOC_PARENT_MEMBER
-- Performing Test PARSEC_HAVE_HWLOC_PARENT_MEMBER - Success
-- Performing Test PARSEC_HAVE_HWLOC_CACHE_ATTR
-- Performing Test PARSEC_HAVE_HWLOC_CACHE_ATTR - Success
-- Performing Test PARSEC_HAVE_HWLOC_OBJ_PU
-- Performing Test PARSEC_HAVE_HWLOC_OBJ_PU - Success
-- Looking for hwloc_bitmap_free in /usr/lib/x86_64-linux-gnu/libhwloc.so
-- Looking for hwloc_bitmap_free in /usr/lib/x86_64-linux-gnu/libhwloc.so - found
-- Found PAPI: /usr/local/lib/libpapi.so  
-- The PAPI Library is found at /usr/local/lib/libpapi.so
-- Found MPI_C: /usr/local/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components: C 
-- PARSEC_FOUND=1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc
-- Assertion type: disable
-- Performing Test HAVE_CRAYXE
-- Performing Test HAVE_CRAYXE - Failed
-- Performing Test HAVE_CRAYXT
-- Performing Test HAVE_CRAYXT - Failed
-- Performing Test HAVE_IBMBGP
-- Performing Test HAVE_IBMBGP - Failed
-- Performing Test HAVE_IBMBGQ
-- Performing Test HAVE_IBMBGQ - Failed
-- Performing Test USE_X86_64_ASM
-- Performing Test USE_X86_64_ASM - Success
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of long double
-- Check size of long double - done
-- Check size of long long
-- Check size of long long - done
-- Performing Test SYS_TYPES_H_HAS_PID_T
-- Performing Test SYS_TYPES_H_HAS_PID_T - Success
-- Looking for memset
-- Looking for memset - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Performing Test CHECK_STDLIB_H_HAS_POSIX_MEMALIGN_THROW
-- Performing Test CHECK_STDLIB_H_HAS_POSIX_MEMALIGN_THROW - Success
-- Looking for pow
-- Looking for pow - not found
-- Looking for random
-- Looking for random - found
-- Looking for sleep
-- Looking for sleep - found
-- Looking for strchr
-- Looking for strchr - found
-- Performing Test HAVE_STD_ABS_LONG
-- Performing Test HAVE_STD_ABS_LONG - Success
-- Performing Test THREAD_LOCAL_SUPPORT
-- Performing Test THREAD_LOCAL_SUPPORT - Success
-- Thread local keyword: thread_local
-- Performing Test RESTRICT_SUPPORT
-- Performing Test RESTRICT_SUPPORT - Failed
-- Performing Test RESTRICT_SUPPORT
-- Performing Test RESTRICT_SUPPORT - Success
-- Restrict keyword: __restrict
-- Performing Test HAVE_UNQUALIFIED_STATIC_DECL
-- Performing Test HAVE_UNQUALIFIED_STATIC_DECL - Success
-- Checking for PIE-disabling linker flags
-- Performing Test LINKER_HAS_DISABLEPIE_SUPPORT
-- Performing Test LINKER_HAS_DISABLEPIE_SUPPORT - Success
-- PIE-disabling linker flags: -no-pie
-- Found LATEX: /usr/bin/latex   
-- Found xterm: /usr/bin/xterm
-- Found gdb: /usr/bin/gdb
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Found MPI_CXX: /usr/local/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI main header: /usr/local/include/mpi.h
-- Found Libunwind: /usr/lib/x86_64-linux-gnu/libunwind.so (found version "1.2.1") 
-- Could NOT find Gperftools (missing: tcmalloc) 
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- === MADNESS Package/Feature Info ===
-- The following features have been enabled:

 * USE_BLAS_LAPACK, Will use BLAS and LAPACK linear algebra distributions via their BLAS++/LAPACK++ interfaces
 * TARGET_MAX_INDEX_RANK=6, default BTAS index type will use stack for rank<=6
 * SPINLOCKS, Enables use of spinlocks instead of mutexes (faster unless over subscribing processors)
 * DQ_PREBUF, Enables thread-local buffer for task aggregation to reduce lock contention
 * BSEND_ACKS, Use MPI Send instead of MPI Bsend for huge message acknowledgements
 * UNITTESTS, Enables unit tests targets
 * FORTRAN_INTEGER_SIZE=4, assumes Fortran integers to be 4 bytes long
 * ASSERTION_TYPE=disable, controls how MADNESS assertions (MADNESS_ASSERT) are handled
 * MPI_THREAD=multiple, controls the level of thread-safety support in MPI

-- The following OPTIONAL packages have been found:

 * Eigen3
 * OpenMP
 * TBB
 * Threads
 * Doxygen
 * LATEX
 * PythonInterp
 * Libunwind

-- The following REQUIRED packages have been found:

 * HWLOC
 * PAPI
 * MPI
 * Git

-- The following features have been disabled:

 * BUILD_DEPS_FROM_SOURCE, Will build missing dependencies from source
 * BUILD_UNITTEST, Will build unit tests
 * ASSERT_THROWS, BTAS_ASSERT(x) will throw if x is false, and not be affected by NDEBUG
 * Elemental, compiles parallel linear-algebra library Elemental as part of MADNESS
 * GENTENSOR, enables use of MRA Function compression that allows computing in 6 dimensions
 * TASK_PROFILER, supports task-level tracing of program execution
 * WORLD_PROFILE, supports simple profiling of MADworld runtime
 * MEM_STATS, gather fine-grained memory statistics (expensive)
 * MEM_PROFILE, instrumented aggregate memory profiling
 * TENSOR_BOUNDS_CHECKING, Enable checking of bounds in tensors ... slow but useful for debugging
 * TENSOR_INSTANCE_COUNT, Enable counting of allocated tensors for memory leak detection
 * NEVER_SPIN, Disables use of spinlocks (notably for use inside virtual machines)
 * WORLD_GET_DEFAULT_DISABLE, Disables World::get_default()
 * TASK_DEBUG_TRACE, supports debug trace of task engine
 * ASSUMES_ASLR_DISABLED, MADNESS runtime assumes the Address Space Layout Randomization (ASLR) to be disabled

-- The following OPTIONAL packages have not been found:

 * cereal
 * CXXStdExecution
 * Gperftools
 * CUDA

-- MADNESS_FOUND=1
-- Found Doxygen: /usr/bin/doxygen (found suitable version "1.8.17", minimum required is "1.8.12") found components: doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/joseph/ttg/build

**Comment by josephjohnjj** [comment]
/home/joseph/ttg/examples/ge/ge_df.cc:25:10: fatal error: madness/world/world.h: No such file or directory
   25 | #include <madness/world/world.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

home/joseph/ttg/examples/floyd-warshall/floyd_warshall_df.cc:34:10: fatal error: madness/world/world.h: No such file or directory
   34 | #include <madness/world/world.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

**Comment by therault** [comment]
Thanks Joseph,

I also need the compilation line: gcc ...
I want to check what -I it's using.

If you don't see the compilation line, try ninja -v if you are using ninja,
or make VERBOSE=1 if using make.

Thanks,
Thomas

**Comment by josephjohnjj** [comment]
cd /home/joseph/ttg/build/_deps/blaspp-build && /usr/bin/g++  -DBLASPP_ID=\"9097d6b\" -Dblaspp_EXPORTS -I/home/joseph/ttg/build/_deps/blaspp-build/include -I/home/joseph/ttg/build/_deps/blaspp-src/include  -O3 -DNDEBUG -fPIC   -Wall -fopenmp -std=c++17 -o CMakeFiles/blaspp.dir/src/axpy.cc.o -c /home/joseph/ttg/build/_deps/blaspp-src/src/axpy.cc
/home/joseph/ttg/examples/ge/ge_df.cc:25:10: fatal error: madness/world/world.h: No such file or directory
   25 | #include <madness/world/world.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

cd /home/joseph/ttg/build/_deps/blaspp-build && /usr/bin/g++  -DBLASPP_ID=\"9097d6b\" -Dblaspp_EXPORTS -I/home/joseph/ttg/build/_deps/blaspp-build/include -I/home/joseph/ttg/build/_deps/blaspp-src/include  -O3 -DNDEBUG -fPIC   -Wall -fopenmp -std=c++17 -o CMakeFiles/blaspp.dir/src/batch_hemm.cc.o -c /home/joseph/ttg/build/_deps/blaspp-src/src/batch_hemm.cc
/home/joseph/ttg/examples/floyd-warshall/floyd_warshall_df.cc:34:10: fatal error: madness/world/world.h: No such file or directory
   34 | #include <madness/world/world.h>

**Comment by evaleev** [comment]
@josephjohnjj this is fixed in master

**Comment by evaleev** [comment]
@josephjohnjj residual serialization issues with these examples also just fixed in master. Sorry, these seemingly were never tested in CI

**Comment by josephjohnjj** [comment]
Thanks! The build was successful.
