### ISSUE TITLE
terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by josephjohnjj** [TESSEorg/ttg#122]
I have a task of task class _agrregator_  that has input dependencies with 8 other task a of different task class. 
```
auto make_aggregator(ttg::Edge<Key, Octant_Aggregator_Data>& octant_aggregator) 
{

  auto f = [=](const Key& key,  Octant_Aggregator_Data& octant_aggregator_data_1,
                                Octant_Aggregator_Data& octant_aggregator_data_2,
                                Octant_Aggregator_Data& octant_aggregator_data_3,
                                Octant_Aggregator_Data& octant_aggregator_data_4,
                                Octant_Aggregator_Data& octant_aggregator_data_5,
                                Octant_Aggregator_Data& octant_aggregator_data_6,
                                Octant_Aggregator_Data& octant_aggregator_data_7,
                                Octant_Aggregator_Data& octant_aggregator_data_8, std::tuple<>& out)
            {
              auto [x, y, z, l, ts, h] = key;

              printf("\n MINIMAR: AGGREGATOR(x=%d, y=%d, z=%d, l=%d, ts=%d)\n", x, y, z, l, ts);
            
            };

  return ttg::wrap<Key>(f, ttg::edges(octant_aggregator,                                                                       
                                      octant_aggregator, 
                                      octant_aggregator, 
                                      octant_aggregator, 
                                      octant_aggregator, 
                                      octant_aggregator,
                                      octant_aggregator,
                                      octant_aggregator), ttg::edges(),"AGREGATOR", {"octant_aggregator_data_1",
                                                                                    "octant_aggregator_data_2",
                                                                                    "octant_aggregator_data_3",
                                                                                    "octant_aggregator_data_4",
                                                                                    "octant_aggregator_data_5",
                                                                                    "octant_aggregator_data_6",
                                                                                    "octant_aggregator_data_7",
                                                                                    "octant_aggregator_data_8"}, {});
}
```

When I run the code I get the error

```
Graph is connected: 1
Graph is connected: 1
AGREGATOR  :  Key(0, 0, 0, 0) : error argument is already set :  1
terminate called after throwing an instance of 'std::logic_error'
  what():  bad set arg
```

Any suggestion as to what I am doing wrong?

**Comment by josephjohnjj** [comment]
This is the task class that sends the data to _agrregator_
```
auto make_octant(ttg::Edge<Key, Key>& treeParent_treeChild, ttg::Edge<Key, Octant_Aggregator_Data>& octant_aggregator) 
{

  auto f = [=](const Key& key,  Key& parent_key, std::tuple<ttg::Out<Key, Octant_Aggregator_Data>>& out)
            {
              stencil(key, parent_key);
            
              ttg::send<0>(Key{parent_key.x, parent_key.y, parent_key.z, parent_key.l, parent_key.ts+1}, 
                Octant_Aggregator_Data{key, parent_key, parent_key.l}, out);
            

            };

  return ttg::wrap<Key>(f, ttg::edges(treeParent_treeChild), ttg::edges(octant_aggregator), "OCTANT", 
    {"parent"}, {"octant_aggregator"});
} 
```

**Comment by devreal** [comment]
@josephjohnjj The error message says that the input of the `aggregator` task has already been set and cannot be set again. Looking at the code, it appears to me that the same edge is used for multiple inputs to aggregator. In that case, sending one output satisfies all of them and the next send in octant will lead to the error message. I'm afraid that you'll need to specify distinct edges for each input of aggregator so that ttg knows how to route an output to one input.

**Comment by therault** [comment]
I agree with Joseph Schuchart: when you write

return ttg::wrap<Key>(f, ttg::edges(octant_aggregator,
                                      octant_aggregator,
                                      octant_aggregator,
                                      octant_aggregator,
                                      octant_aggregator,
                                      octant_aggregator,
                                      octant_aggregator,
                                      octant_aggregator),
ttg::edges(),"AGREGATOR", {"octant_aggregator_data_1",

             "octant_aggregator_data_2",

             "octant_aggregator_data_3",

             "octant_aggregator_data_4",

             "octant_aggregator_data_5",

             "octant_aggregator_data_6",

             "octant_aggregator_data_7",

             "octant_aggregator_data_8"}, {});

You gave each of the octant terminals a different name
(octant_aggregator_data_1, etc...)

but you connect the same edge (octant_aggregator) to these 8 terminals.

**Comment by josephjohnjj** [comment]
Is it possible to have a _gather_ like operation on a task?  I need 8 tasks to send the same kind of data to a single task.
![miniAMR-DAG](https://user-images.githubusercontent.com/6358352/123669011-4cf8e100-d859-11eb-97e2-c1d710dfff74.png)

I am trying to implement a task structure as show in the figure. In the figure only 4 task are shown, but the requirement is the same.

**Comment by devreal** [comment]
@josephjohnjj Is there some form of reduction performed on these 8 inputs? If so, maybe the streaming terminals may help here. I'm not too familiar with them but @pnookala is working on that I believe :)

**Comment by josephjohnjj** [comment]
Not really. I need all the information to be gathered on a single task, so that It can process the information and activated more tasks.

**Comment by devreal** [comment]
In that case I cannot think of any, no. Can you know in advance which output to send into which aggregator input? If not, you may accomplish a more dynamic behavior by keeping an atomic counter for aggregator task inputs and send to the next "free" input. That requires you to do some book keeping by yourself though and reset the counters at the end of the task to allow for the next round.

**Comment by josephjohnjj** [comment]
The tasks that sends the data, to the aggregator, has only one output. So yes, it knows which output is being used to send the data to the aggregator. But it is not sure which input of the aggregator to connect to. 

Is this what you meant?

**Comment by devreal** [comment]
Sorta. In TTG, the sending task has to know which input to send to. So either you can decide based on the Key which input you send to or you do something more dynamic with your own bookkeeping. Either way, you will need to eventually send to 8 different edges and have only one

**Comment by josephjohnjj** [comment]
I did think about embedding the input edge to send to, within the key of the task. But as the Tree grows this becomes a problem. When you meant dynamic bookkeeping, did you mean I should change the manner in which TTG handle an incoming data ? The first data to arrive to the first input, the second to the second input and so on...

**Comment by devreal** [comment]
With dynamic bookkeeping I meant that you keep a counter for the input edge of the aggregator and manage the target input by incrementing the counter. Currently, you need to do this yourself but it might be an interesting addition to TTG eventually :)

**Comment by josephjohnjj** [comment]
Sorry, but I am not sure how to do that. Can you provide a sample of how this would look like?

**Comment by devreal** [comment]
Here is what I have in mind: you keep a `std::map<Key, std::atomic<int>> map` that you can access from your octant tasks. You need to know the key of course when sending. You query the key in the map, increment the atomic counter and then send to that edge:

```C
auto it = map.find(key);
if (it == map.end()) {
  // insert a new key
}
int terminal_id = ++it->second;
```

Remember, the terminal ID is actually a template value so you will have to spell out something like:

```C
switch (terminal_id) {
  case 0: send<0>(...); break;
  case 1: send<1>(...); break;
...
}
```

Then in the aggregator task you probably want to remove the key again from the map. Also, make sure that the accesses are thread-safe by using a mutex.

Then, you need to have 8 distinct edges that connect the octant tasks and the aggregator tasks.

**Comment by josephjohnjj** [comment]
So for each octant key I introduce, I will have a corresponding terminal_id associated with. Got it, Thanks!

**Comment by devreal** [comment]
I was thinking of the Key as being the key for the aggregator task ;) you will end up terminal IDs 0-7 to send to the corresponding output terminal, which then is also then input to the aggregator.

**Comment by josephjohnjj** [comment]
Ok got it. Thanks!

**Comment by evaleev** [comment]
@josephjohnjj to be able to send multiple data items to a particular input terminal of a particular task you need to use a _streaming_ terminal, as @devreal mentioned. What @devreal proposed is basically one of the mechanisms streaming terminal for aggregating data.

Unfortunately, as far as I know (@therault please correct me if I am wrong) the PaRSEC backend has not been taught how to deal with streaming terminals yet ... so @devreal 's workaround is the way to go

P.S. The purpose of a streaming terminal is to process a stream of data, either statically- or dynamically-sized. In your case the size is known to be 8. Then you just do
```
// input 0 will be a streaming terminal that appends received item b into the current result value
op->set_input_reducer<0>([](vector<int> &&a, vector<int> &&b) { a.append(b); });
// terminal will expect 8 items to arrive before firing off the task
// N.B. this is pseudocode, real code right now expects bounds to be key-specific ... this will be fixed when we teach PaRSEC to stream
op->set_argstream_size<0>(8); 
```

**Comment by devreal** [comment]
Ahh yes, when you pass vectors of data you can of course easily aggregate the data in the reducer callback. I need to bring the PaRSEC backend up to support streaming terminals, it's on my list :)

**Comment by josephjohnjj** [comment]
So for the time being I will stick with @devreal solution and then move to steaming terminal when the PaRSEC backend is updated.
