### ISSUE TITLE
Expose built libraries and serialization headers, `parsec_ttg.cc`

### ISSUE THREAD

**Issue by rohanmclure** [TESSEorg/ttg#133]
After building with

```bash
cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=/usr/local/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ \
                -DCMAKE_C_COMPILER=gcc -DBUILD_SHARED_LIBS=OFF && cmake --build . --target install
```

The libraries and headers for serialization in `TTG` still need to be manually copied over to the install prefix. I run the following post installation but am unsure how to cause `cmake` to do this.

```bash
cd ${TTG_BUILD_DIR} && cp ttg/lib* /usr/local/lib/
cd ${TTG_SRC_DIR}/ttg && \
    cp ttg/util/span.h /usr/local/include/ttg/util/ && \
    cp ttg/parsec/ttg_data_copy.h /usr/local/include/ttg/parsec/ && \
    mkdir -p /usr/local/include/ttg/serialization/backends && cp ttg/serialization/*.h /usr/local/include/ttg/serialization/ \
                                                           && cp ttg/serialization/backends/*.h /usr/local/include/ttg/serialization/backends/
```

Also if you built your own PaRSEC runtime, the contents of `ttg/ttg/parsec/parsec_ttg.cc` are not linked in. Would it help to link this into the `libttg.a` library?

Thanks!

**Comment by devreal** [comment]
@rohanmclure Sorry about that, seems like we forgot adding new header files to the installation path. Can you please try https://github.com/TESSEorg/ttg/pull/134 and see if that fixes it?

> Also if you built your own PaRSEC runtime, the contents of ttg/ttg/parsec/parsec_ttg.cc are not linked in. Would it help to link this into the libttg.a library?

I'm not sure I understand. I am building against a self-built extern PaRSEC and have not seen an issue. What is the issue you're seeing?

**Comment by evaleev** [comment]
@rohanmclure #138 has been merged, please test and report whether you can use TTG from the install tree.

N.B. TTG makes it easy to build TTG-based programs while avoiding having to "know" all of its dependencies if using CMake, as shown here: https://github.com/TESSEorg/ttg/blob/master/doc/dox/dev/devsamp/main/CMakeLists.txt

**Comment by rohanmclure** [comment]
Excellent! Sorry about the wait! Yes the libraries and headers have installed, however currently still using a workaround to link in `ttg-parsec`.

> Thanks, I updated the installation of header files in #134. I'm not sure how to accomplish installing the `ttg-parsec` target in a library. The problem seems to be bigger: I don't see `libttg.a`, `libttg-serialization.a`, and `libttg-serialization-madness.a` being installed either. Will have to talk to @evaleev and @therault about this...

**Comment by evaleev** [comment]
@rohanmclure `parsec_ttg.cc` is compiled into  the `ttg-parsec` target ... in your case its archive is probably located at`${TTG_INSTALL_DIR}/lib/libttg-parsec.a` ...

**Comment by rohanmclure** [comment]
So sorry about that! Yes that's all attached and I can compile now. Thanks so much!

**Comment by evaleev** [comment]
@rohanmclure most welcome! Thanks for using TTG.
