### ISSUE TITLE
Existing installation breaks build

### ISSUE THREAD

**Issue by devreal** [TESSEorg/ttg#135]
When specifying an existing installation path via `-DCMAKE_INSTALL_PREFIX` and rerunning CMake the build fails and as it seems that only the tests and examples are being built and BTAS is missing for them.

How to reproduce:

1) Install:

```
$ cmake ../ -DCMAKE_INSTALL_PREFIX=<install-prefix>
# make install
```
(everything is built and installed)

2) Rebuild with same installation prefix:

```
$ rm * -rf
$ cmake ../ -DCMAKE_INSTALL_PREFIX=<install-prefix>
# make
[35/85] Linking CXX executable examples/bspmm-mad
FAILED: examples/bspmm-mad 
: && /usr/bin/g++-10  -g -Wl,--enable-new-dtags -pthread examples/CMakeFiles/bspmm-mad.dir/spmm/spmm.cc.o  -o examples/bspmm-mad  -lBTAS  ttg/libttg.a  ttg/libttg-serialization-madness.a  <install-prefix>/lib/libMADworld.a  /usr/lib/x86_64-linux-gnu/libpapi.so  -latomic  -latomic  /usr/lib/x86_64-linux-gnu/libhwloc.so -Wl,--enable-new-dtags  -lpthread && :
/usr/bin/ld: cannot find -lBTAS
collect2: error: ld returned 1 exit status
```

Note that only 85 targets are being built in the second run, compared to >500 targets in the first run.

**Comment by bosilca** [comment]
Have you cleaned up the install directory specified in CMAKE_INSTALL_PREFIX ?

**Comment by bosilca** [comment]
Assuming that's if you clean it before config. Now what is happening if you clean if after config ?

CMake leave traces about the version of the software it installs. What I think happens here is that the reinstall detects that the same targets have been already build and installed in the install directory, and avoid recompiling them.

**Comment by devreal** [comment]
That works, too: install - clear build directory - run cmake - clear install directory - make

Curiously, if the installation directory, invoking make/ninja reruns cmake. That then cannot find the installation directory anymore and so everything will be build correctly.
