### ISSUE TITLE
Cannot build TTG without Boost

### ISSUE THREAD

**Issue by devreal** [TESSEorg/ttg#179]
Trying to build TTG without boost available fails and there are traces of boost depenencies all over the place. If there is no boost available we should not try to download it but silently ignore it. It's a simple dependency for one of many serialization options, not integral for the project.

**Comment by evaleev** [comment]
@devreal this is likely fixed/no longer relevant?

**Comment by devreal** [comment]
This is fixed, yes. Thanks :+1:
