### ISSUE TITLE
Install target does not install CMake project files or Package Config

### ISSUE THREAD

**Issue by therault** [TESSEorg/ttg#207]
The Install target does not install any file that would help compiling a TTG program that is completely outside the TTG repository.

It currently installs the pkgconfig files for MADNESS and PaRSEC, and the parsecconfig.cmake file, but nothing for TTG.

Should we add something to help users find the TTG package once installed? Or is the only recommended use as a subproject / using a fetch?

**Comment by evaleev** [comment]
@therault it installs `ttg-config.cmake` under `lib/cmake/ttg` ... it is likely needs some TLC but the TTG targets are exported
