### ISSUE TITLE
Unsafe default hash function due to padding bytes/virtual functions

### ISSUE THREAD

**Issue by devreal** [TESSEorg/ttg#239]
While thinking about key hashing for the tutorial, I noticed that we default to a bit-wise FNV hash for non-integral keys. That's nice for usability and works well in some cases but for keys that either have virtual functions or padding bytes we will hash bytes that are not guaranteed to be stable. For example, the bit representation of a key such as

```C
struct Key {
  double x;
  int y;  // followed by 4B padding
};
```

may not be the same after copying the object:

```C
Key k0 = {1.0, 1};
Key k1 = k0;
```
According to https://stackoverflow.com/a/46875219/16791592 the padding bytes in `k0` and `k1` may be different. Applying FNV will yield different hash values. Given that we use the hash value to identify tasks this may lead to unexpected deadlocks if the hashes for the same key differs on different objects of the same key value.

We cannot detect whether a type has padding bytes. I think it would be best to remove the default hash and force users to provide a custom hash function. That's not pretty but it's the safe default.

**Comment by evaleev** [comment]
@devreal [ec4b41e](https://github.com/therault/ttg/commit/ec4b41ef49bd0392b3d086117a862a17591cbc4f) should resolve this
