### ISSUE TITLE
parsec-ttg: distributed runs (messaging)

### ISSUE THREAD

**Issue by therault** [TESSEorg/ttg#36]
The current PaRSEC branch for TTG uses the new active message system to communicate; however it works only for POD and for continuous data, and it relies on arbitrary size active messages, so the code will fail on complex examples.

The system should use AM only for control messages, and on RMA for large or complex data transfers.

**Comment by evaleev** [comment]
@therault is this still pertinent?

**Comment by devreal** [comment]
@evaleev I think the first part is solved (being limited to POD) but it's still using AMs for payload transfer. This is one of the things we'll be looking at this week.

**Comment by evaleev** [comment]
@therault @devreal this is still pending?

**Comment by therault** [comment]
It's not pending anymore, was addressed in PR #87
