### ISSUE TITLE
CMake, subprojects and default targets

### ISSUE THREAD

**Issue by therault** [TESSEorg/ttg#41]
When compiling, if a target is not specified, the Makefile generated by CMake will try to compile the default targets.

Unfortunately, the default targets of each subproject is added to the default targets of TTG. As a consequence, the compilation can be extremely long (compiling all MADNESS binaries and PaRSEC tests).

The solution would be to remove all default targets from the subprojects, but we didn't find how to do this, and the only approach we know would work is to define specific targets in the subprojects themselves (which is invasive), or to make the subproject CMake files detect that they are used as subproject and not define the default targets.

**Comment by evaleev** [comment]
I like the second solution: have MADNESS and PaRSEC use `EXCUDE_FROM_ALL` if `CMAKE_PROJECT_NAME != PROJECT_NAME`

**Comment by evaleev** [comment]
the simpler (and non-intrusive) solution is to set `EXCLUDE_FROM_ALL` target on the TTG top dir.
