### ISSUE TITLE
CMake, subprojects and common targets

### ISSUE THREAD

**Issue by therault** [TESSEorg/ttg#44]
This issue is similar to the Issue #41 : when doing make clean in TTG, the subprojects are also cleaned, which is often an overkill. Ideally, we would have a distclean target (or cleanall? mrproper?) that calls the make clean of the subprojects, and clean should just remove the files compiled in TTG.

**Comment by evaleev** [comment]
the solution is for each subproject to define `target-${PROJECT_NAME}` rather than `target`, (where `target` is `check`, etc.) ... this will unfortunately be intrusive

**Comment by therault** [comment]
Sloved a while ago too...
