### ISSUE TITLE
bin/docker-build.sh Not Building

### ISSUE THREAD

**Issue by rohanmclure** [TESSEorg/ttg#81]
On building with the `bin/docker-build.sh` script which generates a Dockerfile, I get the following error:

```
CMake Error: install(EXPORT "btas" ...) includes target "BTAS" which requires target "Boost_serialization" that is not in any export set.
CMake Error in /home/tesse/ttg-build/_deps/btas-src/CMakeLists.txt:
  export called with target "BTAS" which requires target
  "Boost_serialization" that is not in any export set.
```

I have tried including `apt install -y libboost-serialization-dev`, but the same issue persists.
I have tried debugging what is going on - but don't know quite enough CMake-fu!

I'm having build issues on my local machine, but was hoping to use the built docker image as a basis for rectifying these issues.

**Comment by evaleev** [comment]
@romanmclure feel free to report build issues ... meanwhile please try `docker-build.sh` #85 ... the script now requires architecture param, but otherwise should work as before ... I have tried both amd64 and arm64 and did not manage to reproduce your issue.

**Comment by rohanmclure** [comment]
Thanks for your help here @evaleev, it's looking though that nothing is being written to `/home/tesse/ttg-install` after building. I tried explicitly creating this directory ahead of time but that didn't seem to do anything - the `docker build` completed without populating that directory.

**Comment by evaleev** [comment]
@rohanmclure OK, building the image now actually does install (before it only built TTG). You can run tests/examples once inside the container: `cmake --build /home/tesse/ttg-build --target check`

**Comment by evaleev** [comment]
@rohanmclure fyi: docker fixes were merged into master.

**Comment by rohanmclure** [comment]
Just as a heads' up @evaleev it appears like not all headers are present in the `include` following installation, and so importing `ttg.h` yields:
```
/home/tesse/ttg-install/include/ttg.h:4:10: fatal error: ttg/fwd.h: No such file or directory
    4 | #include "ttg/fwd.h"
      |          ^~~~~~~~~~~
```
