### ISSUE TITLE
Missing headers in install path / include

### ISSUE THREAD

**Issue by rohanmclure** [TESSEorg/ttg#90]
In the provided docker installation, it appears like not all header files are exposed in the `/home/tesse/ttg-install` directory, so a simple `-I/home/tesse/.local/include` won't work for compilation.

```
/home/tesse/ttg-install/include/ttg.h:4:10: fatal error: ttg/fwd.h: No such file or directory
    4 | #include "ttg/fwd.h"
      |          ^~~~~~~~~~~
```

**Comment by evaleev** [comment]
@rohanmclure this should be fixed via #110 ... but there are more fixes for install target on the way
