### ISSUE TITLE
`set_keymap` Unimplemented for PaRSEC Runtime

### ISSUE THREAD

**Issue by rohanmclure** [TESSEorg/ttg#92]
Hoping to assign affinities to MPI ranks for certain tasks, by means of assigning a keymap to certain tasks in order to assign them to certain MPI Ranks.

```C++
auto keymap = [N](const Key& key) { return (int)N; };
set_keymap(keymap);
```

This method stub seems to be unimplemented for the PaRSEC runtime.

**Comment by therault** [comment]
@devreal you have an implementation of this in one of your branches. Can you create a small PR with just this? Or does this pull the entire changes (in which case, we will fix with the large ongoing PR).
