### ISSUE TITLE
GE and Floyd-Warshall Issues

### ISSUE THREAD

**Issue by rohanmclure** [TESSEorg/ttg#96]
With the distributed data variants for GE and Floyd-Warshall, I have not been able to get termination on PaRSEC with multiple ranks using `mpirun -np 2 ./fw-apsp-df-parsec 1024 32 iterative verify-results`, with the same behaviour on GE with `mpirun -np 2 ./ge-df-parsec 1024 32 iterative verify-results`.

We get the same result with `fw-apsp-parsec`, however as this does not apply to a distributed setting (array data is not communicated but transferred via shared memory), we don't expect the example to work (although we would expect it to at least terminate).

I understand that a relevent issue is #93, however would be interested to learn what distinguishes this behaviour from that in `mpirun -np 2 ./sw-parsec -n 2048 -b 32 1`, which does terminate, producing the correct results.

**Comment by bosilca** [comment]
@therault  found a race in the termination detection and proposed a [fix yesterday](https://bitbucket.org/herault/parsec/commits/40dceb35b32ba558dcdac460625cd80ff6ae1ded). Can you try with an updated termdet branch ?

**Comment by therault** [comment]
Yes, please check PR #95, it should solve this issue.

**Comment by rohanmclure** [comment]
Can confirm that #95 fixes termination, with the correct results on the `df` variants of these examples.

**Comment by therault** [comment]
Closed by the merge of PR #95
